language: node_js
cache:
  yarn: true
notifications:
  email: false
node_js:
  - '10'
  - '9'
  - '8'
script:
    - yarn test
    - yarn build
after_success:
  - yarn travis-deploy-once --pro "yarn semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
