language: node_js
cache:
  yarn: true
notifications:
  email: false
node_js:
  - '10'
  - '9'
  - '8'
script:
    - yarn test
    - yarn build
jobs:
  include:
    - stage: test
      script: yarn test
    - stage: build
      script: yarn build
    - stage: release
      script: yarn semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
